# Generated by Django 5.1.2 on 2024-10-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_industry_state_job_job_type_alter_applyjob_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Declined', 'Declined')], max_length=20),
        ),
    ]
