# Generated by Django 5.1.2 on 2024-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_location_job_city_alter_applyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], max_length=20),
        ),
    ]
